# Generated by Django 3.2.1 on 2021-05-05 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_task_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=300)),
                ('email', models.CharField(max_length=50, verbose_name='Email')),
                ('practice', models.CharField(choices=[('US', 'LES MILLS'), ('FR', 'ВОССТАНОВИТЕЛЬНЫЙ ФИТНЕС'), ('CN', 'MIND BODY'), ('RU', 'ЕДИНОБОРСТВА'), ('IT', 'БАССЕЙН'), ('KR', 'КАРДИОТРЕНИРОВКИ')], max_length=300)),
                ('date', models.DateTimeField(verbose_name=' Дата')),
            ],
            options={
                'verbose_name': 'Регистрация на занятие',
            },
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
    ]
