# Generated by Django 3.2.1 on 2021-05-06 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210506_0134'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='adress',
            field=models.CharField(choices=[('АВТОЗАВОДСКИЙ', 'Нижний Новгород, проспект Ленина, 108'), ('БУРНАКОВСКИЙ', 'Нижний Новгород, ул. Бурнаковская, 103а'), ('ДЕЛОВАЯ', 'Нижний Новгород, ул. Родионова, 201, корп. 1'), ('КОРАБЛИ', 'Нижний Новгород, пр. Кораблестроителей, д. 76')], default='default title', max_length=300),
        ),
    ]
