# Generated by Django 3.2.1 on 2021-05-06 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_articles_adress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='adress',
            field=models.CharField(choices=[('АВТОЗАВОДСКИЙ', 'Нижний Новгород, проспект Ленина, 108'), ('БУРНАКОВСКИЙ', 'Нижний Новгород, ул. Бурнаковская, 103а'), ('ДЕЛОВАЯ', 'Нижний Новгород, ул. Родионова, 201, корп. 1'), ('КОРАБЛИ', 'Нижний Новгород, пр. Кораблестроителей, д. 76')], max_length=300),
        ),
    ]
