# Generated by Django 3.2.1 on 2021-05-06 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_articles_adress'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
