# Generated by Django 3.2.1 on 2021-05-06 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_articlenew_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlenew',
            options={'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'Комментарий', 'verbose_name_plural': 'Комментарии'},
        ),
    ]
