# Generated by Django 3.2.1 on 2021-05-06 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20210506_1948'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlenew',
            name='image',
            field=models.ImageField(null=True, upload_to='media', verbose_name='Изображение'),
        ),
    ]
