# Generated by Django 3.2.2 on 2021-05-07 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20210507_0142'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articles',
            options={'verbose_name': 'Регистрация на занятие', 'verbose_name_plural': 'Регистрации на занятия'},
        ),
    ]
